name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
  build-and-upload:
    needs: create-release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Generate SBOM (npm)
        run: npm sbom --output-file=sbom-npm.json
      
      - name: Generate SBOM (Python)
        working-directory: backend
        run: |
          pip install pip-licenses
          pip-licenses --format=json --output-file=../sbom-python.json
      
      - name: Build
        run: npm run build
      
      - name: Build Electron
        run: npm run electron:build
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist-electron/*.exe
            dist-electron/*.dmg
            dist-electron/*.AppImage
            sbom-npm.json
            sbom-python.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
